# HC-AI | ticket: FDD-TOOL-CODEMAP
"""CBM-P2-05/06/07/08: Output formatters for snapshot diff results."""

from __future__ import annotations

import json
from typing import Any

from codebase_map.graph.snapshot_diff import DiffResult


def format_diff_json(result: DiffResult) -> str:
    """Format DiffResult as JSON string (P2-06)."""
    data = _result_to_dict(result)
    return json.dumps(data, indent=2, default=str)


def format_diff_markdown(result: DiffResult) -> str:
    """Format DiffResult as markdown for PR body (P2-05).

    CEO decision: summary table visible + full diff collapsible <details>.
    """
    lines: list[str] = []
    b = result.baseline_meta
    c = result.current_meta
    s = result.summary

    # Header
    lines.append("## Codebase-Map Impact Analysis\n")
    lines.append(
        f"**Baseline:** `{b.get('label', '?')}` "
        f"({b.get('branch', '?')}, "
        f"`{str(b.get('commit_sha', ''))[:7]}`, "
        f"{_fmt_date(b.get('generated_at'))})"
    )
    lines.append(
        f"**Post-dev:** `{c.get('label', '?')}` "
        f"({c.get('branch', '?')}, "
        f"`{str(c.get('commit_sha', ''))[:7]}`, "
        f"{_fmt_date(c.get('generated_at'))})\n"
    )

    # Summary table (always visible)
    lines.append("| Metric | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| Functions added | **{s['functions_added']}** |")
    lines.append(f"| Functions removed | **{s['functions_removed']}** |")
    lines.append(f"| Functions modified | **{s['functions_modified']}** |")
    if s["functions_renamed"] > 0:
        lines.append(f"| Functions renamed | {s['functions_renamed']} |")
    lines.append(f"| Affected callers | **{s['affected_callers']}** |\n")

    if not result.has_changes():
        lines.append("*No structural changes detected.*\n")
        lines.append(
            "Auto-generated by "
            "[codebase-map]"
            "(https://github.com/hypercommerce-vn/codebase-map) CI"
        )
        return "\n".join(lines)

    # Collapsible details
    lines.append("<details>")
    lines.append("<summary>Full Diff Details (click to expand)</summary>\n")

    # Added
    if result.nodes_added:
        lines.append("### Added Functions")
        lines.append("| Function | File | Layer |")
        lines.append("|----------|------|-------|")
        for ch in result.nodes_added[:50]:
            layer = ch.node.layer.value if ch.node.layer else "-"
            lines.append(f"| `{ch.node.name}` | {ch.node.file_path} | {layer} |")

    # Removed
    if result.nodes_removed:
        lines.append("\n### Removed Functions")
        lines.append("| Function | File | Layer |")
        lines.append("|----------|------|-------|")
        for ch in result.nodes_removed[:50]:
            layer = ch.node.layer.value if ch.node.layer else "-"
            lines.append(f"| `{ch.node.name}` | {ch.node.file_path} | {layer} |")

    # Modified
    if result.nodes_modified:
        lines.append("\n### Modified Functions")
        lines.append("| Function | File | Changes |")
        lines.append("|----------|------|---------|")
        for ch in result.nodes_modified[:50]:
            changes = ", ".join(ch.modifications) if ch.modifications else "content"
            lines.append(f"| `{ch.node.name}` | {ch.node.file_path} | {changes} |")

    # Renamed
    if result.nodes_renamed:
        lines.append("\n### Renamed Functions")
        lines.append("| Function | Old File | New File |")
        lines.append("|----------|----------|----------|")
        for ch in result.nodes_renamed:
            lines.append(
                f"| `{ch.node.name}` | {ch.rename_from_file} "
                f"| {ch.node.file_path} |"
            )

    # Affected callers
    if result.affected_callers:
        lines.append("\n### Affected Callers (Tester Focus)")
        lines.append("| Caller | File | Domain | Reason |")
        lines.append("|--------|------|--------|--------|")
        for ac in result.affected_callers[:50]:
            lines.append(
                f"| `{ac.name}` | {ac.file_path} " f"| {ac.domain} | {ac.reason} |"
            )

    lines.append("\n</details>\n")
    lines.append(
        "Auto-generated by "
        "[codebase-map]"
        "(https://github.com/hypercommerce-vn/codebase-map) CI"
    )

    return "\n".join(lines)


def format_diff_text(result: DiffResult) -> str:
    """Format DiffResult as plain text for terminal output."""
    lines: list[str] = []
    s = result.summary

    b = result.baseline_meta
    c = result.current_meta
    lines.append(
        f"Baseline: {b.get('label', '?')} "
        f"({b.get('branch', '?')}, {str(b.get('commit_sha', ''))[:7]})"
    )
    lines.append(
        f"Current:  {c.get('label', '?')} "
        f"({c.get('branch', '?')}, {str(c.get('commit_sha', ''))[:7]})"
    )
    lines.append("")

    if not result.has_changes():
        lines.append("[OK] No structural changes detected.")
        return "\n".join(lines)

    lines.append(f"  Added:    {s['functions_added']}")
    lines.append(f"  Removed:  {s['functions_removed']}")
    lines.append(f"  Modified: {s['functions_modified']}")
    if s["functions_renamed"] > 0:
        lines.append(f"  Renamed:  {s['functions_renamed']}")
    lines.append(f"  Edges +{s['edges_added']} / -{s['edges_removed']}")
    lines.append(f"  Affected callers: {s['affected_callers']}")

    if result.nodes_added:
        lines.append("\n[ADDED]")
        for ch in result.nodes_added[:20]:
            lines.append(f"  + {ch.node.name}  ({ch.node.file_path})")

    if result.nodes_removed:
        lines.append("\n[REMOVED]")
        for ch in result.nodes_removed[:20]:
            lines.append(f"  - {ch.node.name}  ({ch.node.file_path})")

    if result.nodes_modified:
        lines.append("\n[MODIFIED]")
        for ch in result.nodes_modified[:20]:
            mods = ", ".join(ch.modifications)
            lines.append(f"  ~ {ch.node.name}  ({mods})")

    if result.nodes_renamed:
        lines.append("\n[RENAMED]")
        for ch in result.nodes_renamed:
            lines.append(
                f"  > {ch.node.name}  " f"{ch.rename_from_file} -> {ch.node.file_path}"
            )

    if result.affected_callers:
        lines.append(f"\n[AFFECTED CALLERS] ({len(result.affected_callers)})")
        for ac in result.affected_callers[:20]:
            lines.append(f"  ! {ac.name}  ({ac.file_path}) — {ac.reason}")

    return "\n".join(lines)


def filter_breaking_only(result: DiffResult) -> DiffResult:
    """Filter to keep only breaking changes — nodes with affected callers (P2-07)."""
    changed_with_callers: set[str] = set()
    for ac in result.affected_callers:
        changed_with_callers.update(ac.source_changes)

    return DiffResult(
        baseline_meta=result.baseline_meta,
        current_meta=result.current_meta,
        nodes_added=[],  # Added = never breaking
        nodes_removed=[
            c for c in result.nodes_removed if c.node.name in changed_with_callers
        ],
        nodes_modified=[
            c for c in result.nodes_modified if c.node.name in changed_with_callers
        ],
        nodes_renamed=result.nodes_renamed,
        edges_added=[],
        edges_removed=[],
        affected_callers=result.affected_callers,
    )


def format_test_plan(result: DiffResult) -> str:
    """Format affected callers grouped by domain as test plan (P2-08)."""
    lines = ["## Suggested Test Plan\n"]

    if not result.affected_callers:
        lines.append("*No affected callers — no testing required.*")
        return "\n".join(lines)

    # Group by domain
    by_domain: dict[str, list[Any]] = {}
    for ac in result.affected_callers:
        by_domain.setdefault(ac.domain, []).append(ac)

    for domain in sorted(by_domain.keys()):
        callers = by_domain[domain]
        lines.append(
            f"### Domain: {domain.upper()} " f"({len(callers)} functions affected)"
        )
        for ac in callers:
            lines.append(f"- [ ] Test `{ac.name}` — {ac.reason}")
            lines.append(f"  _{ac.file_path}_")
        lines.append("")

    total = len(result.affected_callers)
    domains = len(by_domain)
    lines.append(f"**Total: {total} functions need testing across {domains} domains**")

    return "\n".join(lines)


def _result_to_dict(result: DiffResult) -> dict:
    """Convert DiffResult to a JSON-serializable dict."""
    return {
        "baseline_meta": result.baseline_meta,
        "current_meta": result.current_meta,
        "summary": result.summary,
        "nodes_added": [_node_change_dict(c) for c in result.nodes_added],
        "nodes_removed": [_node_change_dict(c) for c in result.nodes_removed],
        "nodes_modified": [_node_change_dict(c) for c in result.nodes_modified],
        "nodes_renamed": [_node_change_dict(c) for c in result.nodes_renamed],
        "edges_added": [_edge_change_dict(c) for c in result.edges_added],
        "edges_removed": [_edge_change_dict(c) for c in result.edges_removed],
        "affected_callers": [
            {
                "name": ac.name,
                "file_path": ac.file_path,
                "domain": ac.domain,
                "reason": ac.reason,
                "depth": ac.depth,
                "source_changes": ac.source_changes,
            }
            for ac in result.affected_callers
        ],
    }


def _node_change_dict(c: Any) -> dict:
    """Convert a NodeChange to dict."""
    d: dict[str, Any] = {
        "change_type": c.change_type,
        "name": c.node.name,
        "file_path": c.node.file_path,
        "layer": c.node.layer.value if c.node.layer else "",
    }
    if c.modifications:
        d["modifications"] = c.modifications
    if c.old_node:
        d["old_file_path"] = c.old_node.file_path
    if c.rename_from_file:
        d["rename_from_file"] = c.rename_from_file
    return d


def _edge_change_dict(c: Any) -> dict:
    """Convert an EdgeChange to dict."""
    return {
        "change_type": c.change_type,
        "source": c.edge.source,
        "target": c.edge.target,
        "edge_type": c.edge.edge_type.value,
        "is_cascade": c.is_cascade,
    }


def _fmt_date(dt_str: Any) -> str:
    """Format ISO date string to short format."""
    if not dt_str:
        return "?"
    s = str(dt_str)
    if "T" in s:
        return s.split("T")[0]
    return s
