# HC-AI | ticket: MEM-M1-08
"""patterns.md generator — human-readable Markdown from committed patterns."""

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Dict, List, Optional

from knowledge_memory.core.learners.pattern import Pattern

if TYPE_CHECKING:
    from knowledge_memory.verticals.codebase.vault import CodebaseVault

# HC-AI | ticket: MEM-M1-08
# Learner display order and labels
_LEARNER_SECTIONS = [
    ("naming", "Naming Conventions"),
    ("layers", "Layer Architecture"),
    ("ownership", "Code Ownership & Bus Factor"),
]


def generate_patterns_md(
    vault: "CodebaseVault",
    confidence_threshold: float = 60.0,
    output_path: Optional[str] = None,
) -> str:
    """Generate a human-readable patterns.md from vault committed patterns.

    Args:
        vault: CodebaseVault with committed patterns.
        confidence_threshold: Minimum confidence to include (default 60%).
        output_path: If provided, write to this path. Otherwise write to
            vault's default location.

    Returns:
        The generated Markdown string.
    """
    all_patterns = vault.query_patterns()

    # Filter by confidence
    patterns = [p for p in all_patterns if p.confidence >= confidence_threshold]

    # Group by category
    by_category: Dict[str, List[Pattern]] = {}
    for p in patterns:
        by_category.setdefault(p.category, []).append(p)

    # Sort each group by confidence descending
    for cat in by_category:
        by_category[cat].sort(key=lambda p: p.confidence, reverse=True)

    # Build Markdown
    lines: List[str] = []
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines.append("# Codebase Patterns")
    lines.append("")
    lines.append(f"> Generated: {ts}")
    lines.append("> Vertical: codebase")
    lines.append(
        f"> Patterns: {len(patterns)} " f"(threshold: {confidence_threshold}%)"
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    # Emit sections in defined order
    emitted_categories: set = set()
    for category, title in _LEARNER_SECTIONS:
        cat_patterns = by_category.get(category, [])
        if not cat_patterns:
            continue
        emitted_categories.add(category)
        lines.extend(_render_section(title, cat_patterns))

    # Emit any remaining categories not in the predefined order
    for category, cat_patterns in by_category.items():
        if category not in emitted_categories and cat_patterns:
            title = category.replace("_", " ").title()
            lines.extend(_render_section(title, cat_patterns))

    # Footer
    lines.append("---")
    lines.append("")
    lines.append(
        f"*{len(patterns)} patterns discovered · "
        f"Confidence threshold: {confidence_threshold}% · "
        f"Generated by Codebase Memory*"
    )
    lines.append("")

    content = "\n".join(lines)

    # Write to file if vault is initialized
    if output_path:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
    elif vault.vault_dir:
        vert_dir = vault.vault_dir / "verticals" / "codebase"
        vert_dir.mkdir(parents=True, exist_ok=True)
        dest = vert_dir / "patterns.md"
        dest.write_text(content, encoding="utf-8")

    return content


def _render_section(title: str, patterns: List[Pattern]) -> List[str]:
    """Render a section of patterns as Markdown lines."""
    lines: List[str] = []
    lines.append(f"## {title}")
    lines.append("")

    for p in patterns:
        lines.extend(_render_pattern(p))

    return lines


# HC-AI | ticket: MEM-M1-08
def _render_pattern(pattern: Pattern) -> List[str]:
    """Render a single pattern as Markdown lines."""
    lines: List[str] = []
    # Pattern header
    display_name = pattern.name.replace("::", " › ").replace("_", " ")
    lines.append(f"### {display_name}")
    lines.append("")

    # Confidence + evidence count
    ev_count = len(pattern.evidence) if pattern.evidence else 0
    lines.append(
        f"**Confidence:** {pattern.confidence:.0f}% · "
        f"**Evidence:** {ev_count} items"
    )
    lines.append("")

    # Category-specific rendering
    if pattern.category == "naming":
        lines.extend(_render_naming_detail(pattern))
    elif pattern.category == "layers":
        lines.extend(_render_layers_detail(pattern))
    elif pattern.category == "ownership":
        lines.extend(_render_ownership_detail(pattern))
    else:
        # Generic metadata dump
        lines.extend(_render_generic_detail(pattern))

    lines.append("")
    return lines


def _render_naming_detail(pattern: Pattern) -> List[str]:
    """Render naming-specific pattern details."""
    lines: List[str] = []
    meta = pattern.metadata

    if "dominant_case" in meta:
        target = meta.get("target", "")
        dominant = meta.get("dominant_case", "")
        compliance = meta.get("compliance_pct", 0)
        violations = meta.get("violation_count", 0)
        lines.append(
            f"> **{target}**: {dominant} convention at {compliance}% compliance"
        )
        if violations > 0:
            violation_names = meta.get("violations", [])
            lines.append(
                f"> ⚠️ {violations} violations: {', '.join(violation_names[:5])}"
            )
            if violations > 5:
                lines.append(f">   ...and {violations - 5} more")
        # Case distribution
        dist = meta.get("case_distribution", {})
        if dist:
            parts = [f"{case}: {count}" for case, count in dist.items()]
            lines.append(f"> Distribution: {' · '.join(parts)}")

    elif "prefix_distribution" in meta or "crud_coverage_pct" in meta:
        coverage = meta.get("crud_coverage_pct", 0)
        lines.append(f"> CRUD prefix coverage: {coverage}% of service methods")
        dist = meta.get("prefix_distribution", {})
        if dist:
            parts = [f"`{prefix}` ({count})" for prefix, count in dist.items()]
            lines.append(f"> Prefixes: {', '.join(parts)}")

    elif "top_prefixes" in meta:
        prefixes = meta.get("top_prefixes", {})
        total = meta.get("total_functions", 0)
        parts = [f"`{p}` ({c})" for p, c in prefixes.items()]
        lines.append(f"> Top prefixes across {total} functions: {', '.join(parts)}")

    return lines


def _render_layers_detail(pattern: Pattern) -> List[str]:
    """Render layer-specific pattern details."""
    lines: List[str] = []
    meta = pattern.metadata

    if "layer_pct" in meta:
        lines.append("> **Layer distribution:**")
        pct = meta.get("layer_pct", {})
        for layer, p in sorted(pct.items(), key=lambda x: x[1], reverse=True):
            bar = "█" * max(1, int(p / 5))
            lines.append(f"> {bar} {layer}: {p}%")
        recognized = meta.get("recognized_pct", 0)
        lines.append(f"> Recognition rate: {recognized}%")

    elif "compliance_pct" in meta:
        compliance = meta.get("compliance_pct", 0)
        mismatches = meta.get("mismatch_count", 0)
        lines.append(f"> Layer compliance: {compliance}%")
        if mismatches > 0:
            samples = meta.get("mismatched_samples", [])
            lines.append(f"> ⚠️ {mismatches} mismatched files:")
            for s in samples[:5]:
                lines.append(
                    f">   - `{s.get('file_path', '')}`: "
                    f"detected={s.get('detected', '')} vs stored={s.get('stored', '')}"
                )

    elif "total_domains" in meta and "domains" in meta:
        total = meta.get("total_domains", 0)
        multi = meta.get("multi_layer_domains", 0)
        lines.append(f"> {total} domains detected, {multi} with multi-layer structure")
        domains = meta.get("domains", [])
        for d in domains[:5]:
            layers = d.get("layers", {})
            layer_str = ", ".join(f"{k}({v})" for k, v in layers.items())
            lines.append(
                f">   - **{d['domain']}**: {d['node_count']} nodes [{layer_str}]"
            )

    elif "depth_stats" in meta:
        stats = meta.get("depth_stats", {})
        lines.append("> **Nesting depth per layer:**")
        for layer, s in stats.items():
            lines.append(
                f">   - {layer}: avg {s['avg_depth']}, "
                f"range {s['min_depth']}-{s['max_depth']} ({s['count']} files)"
            )

    elif "hotspot_dirs" in meta:
        hotspots = meta.get("hotspot_dirs", {})
        lines.append("> **Hotspot directories:**")
        for d, count in hotspots.items():
            lines.append(f">   - `{d}`: {count} nodes")

    return lines


def _render_ownership_detail(pattern: Pattern) -> List[str]:
    """Render ownership-specific pattern details."""
    lines: List[str] = []
    meta = pattern.metadata

    if "single_owner_count" in meta:
        total = meta.get("total_files", 0)
        single = meta.get("single_owner_count", 0)
        pct = meta.get("single_owner_pct", 0)
        lines.append(
            f"> {single}/{total} files ({pct}%) have a single "
            f"dominant author (>80% commits)"
        )
        top_files = meta.get("top_single_owner_files", [])
        if top_files:
            lines.append("> Top single-owner files:")
            for f in top_files[:5]:
                lines.append(f">   - `{f['file']}`: {f['author']} ({f['pct']}%)")

    elif "top_authors" in meta:
        total = meta.get("total_commits", 0)
        authors = meta.get("top_authors", [])
        lines.append(f"> **Top contributors** ({total} total commits):")
        for a in authors[:5]:
            bar = "█" * max(1, int(a["pct"] / 5))
            lines.append(f"> {bar} {a['author']}: {a['commits']} commits ({a['pct']}%)")

    elif "risk_domains" in meta:
        risk_count = meta.get("risk_domain_count", 0)
        total = meta.get("total_domains", 0)
        if risk_count > 0:
            lines.append(
                f"> ⚠️ **{risk_count}/{total} domains at risk** (bus factor = 1):"
            )
            for d in meta.get("risk_domains", [])[:5]:
                lines.append(
                    f">   - **{d['domain']}**: {d['top_author']} owns "
                    f"{d['top_author_pct']}% ({d['file_count']} files)"
                )
        healthy = meta.get("healthy_domains", [])
        if healthy:
            lines.append("> ✅ Healthy domains (bus factor ≥ 2):")
            for d in healthy[:5]:
                lines.append(
                    f">   - {d['domain']}: bus factor={d['bus_factor']}, "
                    f"{d['total_authors']} authors"
                )

    elif "specialist_count" in meta:
        specialists = meta.get("specialist_count", 0)
        generalists = meta.get("generalist_count", 0)
        total = meta.get("total_authors", 0)
        pct = meta.get("specialist_pct", 0)
        lines.append(
            f"> {specialists}/{total} authors ({pct}%) are specialists "
            f"(contribute to only 1 domain)"
        )
        if generalists > 0:
            lines.append(f"> {generalists} generalists (contribute to 3+ domains)")
        spec_list = meta.get("specialists", [])
        if spec_list:
            for s in spec_list[:5]:
                lines.append(f">   - {s['author']}: {s['domain']} only")

    return lines


def _render_generic_detail(pattern: Pattern) -> List[str]:
    """Render generic pattern metadata."""
    lines: List[str] = []
    meta = pattern.metadata
    if meta:
        for key, value in list(meta.items())[:5]:
            lines.append(f"> {key}: {value}")
    return lines
